enableTelemetry: false

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.6.3.cjs

npmPublishAccess: public
npmPublishRegistry: 'https://git.ftc.ru/api/v4/projects/5712/packages/npm/'
npmRegistryServer: 'http://webdev-docker.ftc.ru:8081/repository/npm-group/'
npmAuditRegistry: 'http://webdev-docker.ftc.ru:8081/repository/npm-group/'
npmAlwaysAuth: true

npmRegistries:
    //git.ftc.ru/api/v4/projects/5712/packages/npm/:
        npmAlwaysAuth: true
        npmAuthToken: '${CI_JOB_TOKEN:-glpat--kgmynEwoxDQKLqWUGxR}'
    '//webdev-docker.ftc.ru:8081/repository/npm-group/':
        npmAlwaysAuth: false
